[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fuzz_runs = 10000
invariant_runs = 1000
invariant_depth = 100
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
